# vim: set filetype=dockerfile
FROM localhost/local-ai-chat-lightspeed-stack:latest

USER root

ADD ./llama-stack /app-root/llama-stack

RUN python3.12 -m ensurepip

RUN cd /app-root/llama-stack && python3.12 -m pip install --editable .

RUN cd /app-root/ && python3.12 -m pip install .

RUN python3.12 -m pip install pyyaml pyaml

RUN python3.12 -m pip install litellm

RUN python3.12 -m pip install sqlalchemy

RUN python3.12 -m pip install mcp

RUN python3.12 -m pip install faiss-cpu sentence_transformers

EXPOSE 8080
